name: Test and Build

on:
  pull_request:
    branches: ['main']

jobs:
  test:
    name: Run Tests
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - name: Typecheck
        run: pnpm run typecheck
      - name: Test
        run: pnpm run test -- --runInBand
  
  build_ios:
    name: Build iOS
    needs: [test]
    type: build
    params:
      platform: ios
      profile: preview
  
  build_android:
    name: Build Android
    needs: [test]
    type: build
    params:
      platform: android
      profile: preview
